#
# ***************
# * _config.yml *
# ***************
#


# Standard Settings

title: 1st Example Scouts # Make this your group name.
email: you@youremail.com # Your email.
url: "examplescouts.org" # The domain name your sit will live at.
plugins:
  - jekyll-remote-theme

  
# Theme Settings

#theme: jekyll-theme-be-prepared # Uncomment this line to use be-prepared as a gem theme.
remote_theme: newlongtonscouts/jekyll-theme-be-prepared # You can use @ and then a version number to specify a specific build.
stylesheet: custom.css


# Version Settings

repo: newlongtonscouts/be-prepared-template # The GitHub repository where your GitHub pages site lives.
majorversion: 0
releasedatetime: 2024-01-01T00:00:00Z # The release date and time of the current major version.
# manualversion: 1.0.0 # Uncomment this if you're not hosting your site on GitHub pages (or if you want to use proper numbering).


# Misc. Settings

devbanner: true # Set to false to hide the yellow sticky banner. You can edit the contents of the banner by adding _includes/devbanner.html
instagram: https://www.instagram.com/scouts/ # The full address of your Instagram page if you want to use the default Socials link.